export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_CHECK = 'AUTH_CHECK';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const FETCH_COMMENTS_REQUEST = "FETCH_COMMENTS_REQUEST";
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCES";
export const FETCH_COMMENTS_FAILURE = "FETCH_COMMENTS_FAILURE";


export const ADD_COMMENTS = "ADD_COMMENTS"
export const DELETE_COMMENTS = "DELETE_COMMENTS"
export const EDIT_COMMENTS = "EDIT_COMMENTS"

export const INCREMENT_LIKES = "INCREMENT_LIKES"
export const DECREMENT_LIKE = "DECREMENT_LIKE"

export const INCREMENT_FOLLOWERS = "INCREMENT_FOLLOWERS"
export const DECREMENT_FOLLOWERS = "DECREMENT_FOLLOWERS"